### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by TechnologyClassroom** [BrainStormYourWayIn/sierra#6]
The `Copyright License Used` section if the doc and README talks of copyright and all rights reserved.  There is a LICENSE file that says Apache-2.0.  When using a free software license, typically you claim copyright and then release rights based on the license that is chosen.

I would suggest renaming that section to simply `License` and add a notice about Apache 2 on the last line of the section and remove the all rights reserved line.

**Comment by pranavr2003** [comment]
I'm actually quite new to licensing and issues surrounding it, so let me make sure I get this. You're suggesting I change `Copyright License Used` to simply `License`, remove the 'All rights reserved' line?

**Comment by Siddhesh-Agarwal** [comment]
@TechnologyClassroom does [this pull request](https://github.com/BrainStormYourWayIn/sierra/pull/7) address your issue?

**Comment by TechnologyClassroom** [comment]
@pranavr2003 @Siddhesh-Agarwal That PR is a good start.  [Pandas uses that wording](https://github.com/pandas-dev/pandas/blob/master/LICENSE) and then follows it up with BSD 3 clause license.  Stating copyright without the license is misleading and would normally be interpreted as proprietary copyright which is not what pandas intends.

If the code that you based this project on is BSD 3 clause, maybe that would be a better license choice than Apache-2.0.

**Comment by pranavr2003** [comment]
@TechnologyClassroom I understand ya now. BSD C3 is too restrictive, so we'll stick with Apache 2.0 and your changes. Thanks.

**Comment by pranavr2003** [comment]
Just to clarify, is the PR exactly what you're suggesting?

**Comment by TechnologyClassroom** [comment]
@pranavr2003 No, the PR is part of what I suggested.  I also suggested:

> add a notice about Apache 2 on the last line of the section

because

> Stating copyright without the license is misleading and would normally be interpreted as proprietary copyright which is not what pandas intends.

I am not a lawyer.  Why is BSD 3 Clause too restrictive?  I think that Apache-2.0 and BSD 3 Clause are too permissive as downstream projects are typically proprietary.

**Comment by pranavr2003** [comment]
That's not my opinion, actually. It's given on the Pandas website. Strange and debatable.

**Comment by pranavr2003** [comment]
Is the current PR what you're suggesting?

**Comment by TechnologyClassroom** [comment]
Pandas uses BSD 3 clause and states on their website that it is too restrictive?

**Comment by TechnologyClassroom** [comment]
I see the new PR.  That is good.
